language: go
go:
  - 1.11.x
  - 1.12.x
  - master
env:
  global:
    - DEP_VERSION="0.5.0"
    - PATH=/snap/bin:$PATH
services:
  - docker
addons:
  apt:
    packages:
      - rpm
      - snapd
before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
    -in snap.login.enc -out snap.login -d
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
    -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - make setup
  - sudo snap install snapcraft --classic
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: osxg
      osx_image: xcode10
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    verbose: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
      master: true
